language: go
sudo: required
services:
  - docker
script:  make
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - "*.rpm"
    - "*.deb"
  skip_cleanup: true
  on:
    tags: true